### ISSUE TITLE
Issue with Node.JS runtime

### ISSUE THREAD

**Issue by qb411** [aws-samples/aws-cfn-windows-hpc-template#2]
We have found another issue with the script.  This is due to the runtime for nodejs:
```
"FindSnapshotFunction": {
			"Type" : "AWS::Lambda::Function",
			"Properties" : {
				"Code" : {
					"S3Bucket" : "<BUCKETNAME>",
					"S3Key" : "lambda/find-snapshot.zip"
				},
				"Description" : "AWS Lambda function for searching snapshot based on name",
				"Handler" : "find-snapshot.handler",
				"MemorySize" : "128",
				"Role" : { "Fn::GetAtt" : [ "FindSnapshotRole", "Arn" ] },
				"Runtime" : "**nodejs**",
				"Timeout" : "25"
}

```

The NODEJS runtime must now be changed to "nodejs4.3" for the runtime.   Othewise the script will fail to run properly from within Lambda.

**Comment by cpollard0** [comment]
Thanks for the report @qb411. We've updated the repository and no longer have a dependency on the find snapshot function.
