### ISSUE TITLE
Issue with SnapshotID parameter in 2-cluster.json

### ISSUE THREAD

**Issue by petersonsbuild** [aws-samples/aws-cfn-windows-hpc-template#3]
{
	"AWSTemplateFormatVersion" : "2010-09-09",
	"Description"              : "This CloudFormation stack creates a Microsoft HPC Pack 2012 R2 Cluster in an existing environment. **WARNING** This template creates two or more Amazon EC2 instances. You will be billed for the AWS resources used if you create a stack from this template.",
	"Parameters"               : {
		"KeyName" : {
			"Description": "Name of an existing EC2 Key Pair",
			"Type"       : "String",
			"Default"    : ""
		},
		"SnapshotID" : {
			"Description"          : "Snapshot Id of the HPC Installation data",
			"Type"                 : "String",
			"AllowedPattern"       : "snap-([0-9a-fA-F]{8})",
			"ConstraintDescription": "must be a valid snapshot ID."
		},

Under SnapshotID, the "AllowedPattern" parameter failed for me. Granted, I had to copy my snapshot between regions, and I noticed the replicated snapshotID was larger than the original. So, I changed line 13 of the json file to this:

"AllowedPattern"       : "snap-([0-9a-zA-Z]*)"

So the final version looks like this:

{
	"AWSTemplateFormatVersion" : "2010-09-09",
	"Description"              : "This CloudFormation stack creates a Microsoft HPC Pack 2012 R2 Cluster in an existing environment. **WARNING** This template creates two or more Amazon EC2 instances. You will be billed for the AWS resources used if you create a stack from this template.",
	"Parameters"               : {
		"KeyName" : {
			"Description": "Name of an existing EC2 Key Pair",
			"Type"       : "String",
			"Default"    : ""
		},
		"SnapshotID" : {
			"Description"          : "Snapshot Id of the HPC Installation data",
			"Type"                 : "String",
			"AllowedPattern"       : "snap-([0-9a-zA-Z]*)",
			"ConstraintDescription": "must be a valid snapshot ID."
		},

**Comment by cpollard0** [comment]
Hi @plbenpeterson, we've updated the solution to one that uses HPC Pack 2019 with different mechanisms for standing up the resources. The reported issue is no longer relevant. Thank you for reporting it, and please let us know if there are any issues with the updated template.
